/**
 * Minimal valid image fixtures for E2E upload tests.
 *
 * Each constant is a Buffer containing the smallest valid encoding of its
 * format that passes SixLabors.ImageSharp's decoder (used by the backend to
 * process uploads before storage).
 *
 * The PNG / JPEG / WebP bytes were generated by SixLabors.ImageSharp 3.x
 * (see /tmp/gen-images/).  The GIF is the well-known 1×1 transparent GIF89a
 * that also passes ImageSharp.  Regenerate if you need to update them.
 */

/**
 * 1 × 1 RGBA PNG, 84 bytes.
 * Generated by SixLabors.ImageSharp 3.x — passes the CRC checks that the
 * original hand-crafted fixture did not.
 */
export const MINIMAL_PNG: Buffer = Buffer.from(
  '89504e470d0a1a0a0000000d4948445200000001000000010806' +
  '0000001f15c489000000097048597300000ec400000ec401952b' +
  '0e1b0000000b49444154789c63f90f04000a0f04016cc637a700' +
  '00000049454e44ae426082',
  'hex',
)

/**
 * 1 × 1 white JPEG / JFIF, ~615 bytes.
 * Generated by SixLabors.ImageSharp 3.x.
 * Magic: FF D8 FF (JPEG SOI + marker).
 */
export const MINIMAL_JPEG: Buffer = Buffer.from(
  '/9j/4AAQSkZJRgABAQEAYABgAAD/wAARCAABAAEDASIAAhEBAxEB' +
  '/8QBogAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoLEAACAQMD' +
  'AgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHB' +
  'FVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNU' +
  'VVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJma' +
  'oqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj' +
  '5OXm5+jp6vHy8/T19vf4+foBAAMBAQEBAQEBAQEAAAAAAAABAgME' +
  'BQYHCAkKCxEAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdh' +
  'cRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2' +
  'Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOE' +
  'hYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbH' +
  'yMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9sAhAAIBgYH' +
  'BgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMc' +
  'HCg3KSwwMTQ0NB8nOT04MjwuMzQyAQkJCQwLDBgNDRgyIRwhMjIy' +
  'MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy' +
  'MjIyMjIyMjL/2gAMAwEAAhEDEQA/APf6KKKAP//Z',
  'base64',
)

/**
 * 1 × 1 transparent GIF 89a, 35 bytes.
 * Magic: 47 49 46 38 39 61 ("GIF89a").
 * This is the well-known minimal GIF and passes SixLabors.ImageSharp.
 */
export const MINIMAL_GIF: Buffer = Buffer.from(
  'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
  'base64',
)

/**
 * 1 × 1 lossy WebP, ~54 bytes.
 * Generated by SixLabors.ImageSharp 3.x.
 * Magic: 52 49 46 46 ... 57 45 42 50 ("RIFF…WEBP").
 */
export const MINIMAL_WEBP: Buffer = Buffer.from(
  'UklGRi4AAABXRUJQVlA4ICIAAABQAgCdASoBAAEALmk0mk0kJCQkBABoS0gABuAA/vuUAAAA',
  'base64',
)

/** Small fake MP4 ftyp-box prefix — not a playable video, but has MP4 magic bytes. */
export const FAKE_MP4: Buffer = Buffer.from(
  '0000001866747970 6d703432 00000000 6d703432 69736f6d'.replace(/\s/g, ''),
  'hex',
)

/** 3 bytes of garbage — useful for wrong-format negative tests. */
export const GARBAGE_BYTES: Buffer = Buffer.from([0x00, 0x01, 0x02])
