using Omnijoy.Core.DTOs.Places;

namespace Omnijoy.Core.Interfaces;

/// <summary>
/// Thin proxy to the Google Places API. The implementation lives in
/// Infrastructure and injects a named <c>HttpClient</c> ("GooglePlaces")
/// configured with the correct base address. The API key is read from
/// configuration (<c>Google:PlacesApiKey</c>) and never exposed to the
/// browser.
/// </summary>
public interface IPlacesProxyService
{
    /// <summary>
    /// Returns autocomplete predictions for the given <paramref name="input"/> text.
    /// </summary>
    /// <param name="input">Partial address / place name typed by the user.</param>
    /// <param name="types">
    /// Google Places type filter — e.g. <c>"(cities)"</c> for a location picker
    /// or <c>"(address)"</c> for a street-address picker.
    /// Null / empty = no type filter.
    /// </param>
    /// <param name="sessionToken">
    /// Optional session token (UUID) generated by the client at the start of
    /// each autocomplete session. Forward to Google so that all keystrokes in
    /// the same session plus the final Details call are billed as a single
    /// geocode request.
    /// </param>
    /// <returns>
    /// List of predictions (may be empty). Returns an empty list — never
    /// throws — when the API key is not configured.
    /// </returns>
    Task<IReadOnlyList<PlaceAutocompleteResultDto>> GetAutocompleteAsync(
        string  input,
        string? types,
        string? sessionToken);

    /// <summary>
    /// Resolves a <paramref name="placeId"/> to structured location data
    /// (formatted address, city, country, coordinates).
    /// </summary>
    /// <param name="placeId">A Google Places place_id previously obtained from autocomplete.</param>
    /// <param name="sessionToken">
    /// The session token used during the autocomplete phase. Providing the same
    /// token here closes the billing session. After this call the token must
    /// not be reused.
    /// </param>
    /// <returns>
    /// Place details, or <see langword="null"/> when the API key is not
    /// configured or the place_id is not found.
    /// </returns>
    Task<PlaceDetailsDto?> GetDetailsAsync(string placeId, string? sessionToken);
}
