using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Omnijoy.Api.RateLimiting;
using Omnijoy.Core.Interfaces;

namespace Omnijoy.Api.Controllers;

/// <summary>
/// Backend proxy for the Google Places API so that the API key is never
/// exposed client-side.  All endpoints require authentication to prevent
/// quota abuse from anonymous callers.
///
/// <para>Session tokens (UUIDs) should be generated by the client at the
/// start of each autocomplete session (first keystroke) and forwarded on
/// every <c>/autocomplete</c> call plus the final <c>/details/{placeId}</c>
/// call.  This way Google bills a single geocode request per search rather
/// than one per keystroke.</para>
/// </summary>
[ApiController]
[Route("api/places")]
[Authorize]
[EnableRateLimiting(RateLimitConstants.StrictPolicy)]
public class PlacesController : ControllerBase
{
    private readonly IPlacesProxyService _places;

    public PlacesController(IPlacesProxyService places)
    {
        _places = places;
    }

    // ── GET /api/places/autocomplete ─────────────────────────────────────────

    /// <summary>
    /// Returns autocomplete predictions for the given <paramref name="input"/> text.
    /// </summary>
    /// <param name="input">Partial address / place name.</param>
    /// <param name="types">
    /// Google Places type filter — e.g. <c>(cities)</c> for a user location picker
    /// or <c>(address)</c> for an event / company address picker.
    /// Omit to return all place types.
    /// </param>
    /// <param name="sessiontoken">
    /// Client-generated UUID session token.  Forward on every call within the
    /// same autocomplete session to minimise API billing.
    /// </param>
    /// <returns>
    /// Array of <c>{ placeId, description, mainText, secondaryText }</c>.
    /// Returns an empty array (200 OK) when the Google API key is not
    /// configured, so dev environments without a key do not break.
    /// </returns>
    [HttpGet("autocomplete")]
    [AllowAnonymous]
    public async Task<IActionResult> Autocomplete(
        [FromQuery] string? input,
        [FromQuery] string? types        = null,
        [FromQuery] string? sessiontoken = null)
    {
        if (string.IsNullOrWhiteSpace(input))
            return BadRequest(new { error = "Query parameter 'input' is required." });

        var results = await _places.GetAutocompleteAsync(input, types, sessiontoken);
        return Ok(results);
    }

    // ── GET /api/places/details/{placeId} ────────────────────────────────────

    /// <summary>
    /// Resolves a <paramref name="placeId"/> to structured location data.
    /// </summary>
    /// <param name="placeId">A Google Places <c>place_id</c> from a prior autocomplete call.</param>
    /// <param name="sessiontoken">
    /// The session token used during autocomplete.  Providing the same token
    /// here closes the billing session.  After this call the token must not
    /// be reused.
    /// </param>
    /// <returns>
    /// <c>{ placeId, formattedAddress, city, country, countryCode, latitude, longitude }</c>,
    /// or 404 when the API key is not configured or the place is not found.
    /// </returns>
    [HttpGet("details/{placeId}")]
    [AllowAnonymous]
    public async Task<IActionResult> Details(
        [FromRoute] string  placeId,
        [FromQuery] string? sessiontoken = null)
    {
        if (string.IsNullOrWhiteSpace(placeId))
            return BadRequest(new { error = "placeId is required." });

        var details = await _places.GetDetailsAsync(placeId, sessiontoken);
        if (details is null)
            return NotFound(new { error = "Place not found or API key not configured." });

        return Ok(details);
    }
}
